[WIP] Added mongodb for storing migration data, celery for async copy data
raccoongang/openprocurement.documentservice pull request #1
Opened 2017-06-12 12:56 UTC by dimka2014

2017-06-22 07:34 UTC, dixon-che commented on openprocurement/documentservice/__init__.py
> +    config.registry.db = DatabaseWrapper(settings.get('mongo_url'), storage)
А ты нашел где вообще есть шаблоны настроек? От куда они разворачиваются? Я так понимаю надо бы в них тоже включить описание, что там должны быть такие вот параметры. А если этих параметров нет, то мы в монгу ничего не пишем и таски не ставим, а просто логируем ворнинги в файлы, что такой-то файл загружен, но не синхронизирован.

2017-06-22 07:34 UTC, dixon-che commented on openprocurement/documentservice/views.py
> +TASK_COPY_DOCUMENT = 'task.copy_document'
Это просто название таска который описан в воркере? В текущем репозитории/проекте нам не нужно определение этой функции?

2017-06-23 20:32 UTC, dixon-che requested changes

2017-06-23 20:32 UTC, dixon-che commented on openprocurement/documentservice/data_sync.py
> +                LOGGER.warn(err, exc_info=True)
Не нахожу такой функции...
https://docs.python.org/2/library/logging.html#logging.warning

2017-06-23 20:32 UTC, dixon-che commented on openprocurement/documentservice/data_sync.py
> +LOGGER = getLogger(__name__)
Мне кажется, что капслок не подходит, это же не константа.

2017-06-23 20:32 UTC, dixon-che commented on openprocurement/documentservice/data_sync.py
> +        if not self.celery:
Мне кажется тут ошибка и должно быть 
`if not self.sync_enabled:`

2017-06-23 20:32 UTC, dixon-che commented on openprocurement/documentservice/tests/main.py
> +        self.app.app.registry.data_sync_manager.sync_document_register.assert_called()
Не понимаю как это работает, объясни. Или это просто проверка после мока, что такая функция в принципе была вызвана?

2017-06-23 20:54 UTC, dimka2014 commented on openprocurement/documentservice/data_sync.py
> +LOGGER = getLogger(__name__)
согласен, что не подходит, но лучше когда везде одинаково, чем разное
https://github.com/raccoongang/openprocurement.documentservice/blob/master/openprocurement/documentservice/views.py#L10

2017-06-23 20:58 UTC, dimka2014 commented on openprocurement/documentservice/data_sync.py
> +                LOGGER.warn(err, exc_info=True)
это краткий синоним warning https://github.com/python/cpython/blob/2.7/Lib/logging/__init__.py#L1181 хотя я вот сейчас увидел что в 3-м питоне этот метод deprecated поэтому логично изменить на warning, спасибо

2017-06-23 21:03 UTC, dimka2014 commented on openprocurement/documentservice/data_sync.py
> +        if not self.celery:
это расчет на то что при инициализации celery вылетел exception и celery не инициализировалась, проверка на sync_enabled выполнена в sync_document_register и sync_document_upload

2017-06-23 21:03 UTC, dimka2014 commented on openprocurement/documentservice/tests/main.py
> +        self.app.app.registry.data_sync_manager.sync_document_register.assert_called()
просто проверка что функция была вызвана

2017-06-23 21:35 UTC, dixon-che commented on openprocurement/documentservice/data_sync.py
> +LOGGER = getLogger(__name__)
Безобразно, но однообразно... вот засада. Конечно руки чешуться везде поменять, интересно как оно в остальных проектах/репозиториях?

2017-06-23 21:38 UTC, dixon-che commented on openprocurement/documentservice/data_sync.py
> +        if not self.celery:
Что-то не пойму расчета, если sync_enabled - False, и self.celery не будет инициализировано, то оно с attributeerror должно тут упасть.

2017-06-23 21:47 UTC, dimka2014 commented on openprocurement/documentservice/data_sync.py
> +        if not self.celery:
c attribute error ничего не упадет, т.к. celery - изначально инициализируется None, а если sync_enabled False то до этой строчки не дойдет, отсечется в https://github.com/raccoongang/openprocurement.documentservice/blob/89a49d743c542ad093a45e87ed2baaaeb27ecf07/openprocurement/documentservice/data_sync.py#L49 или
https://github.com/raccoongang/openprocurement.documentservice/blob/89a49d743c542ad093a45e87ed2baaaeb27ecf07/openprocurement/documentservice/data_sync.py#L39

2017-06-23 21:49 UTC, dimka2014 commented on openprocurement/documentservice/data_sync.py
> +LOGGER = getLogger(__name__)
мне кажется в других проектах, репах не очень важно, как по мне важно однообразие внутри одной репы, пусть и не всегда соответствующее код стайлу

2017-06-23 21:55 UTC, dixon-che commented on openprocurement/documentservice/data_sync.py
> +LOGGER = getLogger(__name__)
Давай везде поменяем? Тут всего-то файлов до десятка. Или на приемке пул-реквеста отгребем проблем?

2017-06-23 21:55 UTC, dixon-che commented on openprocurement/documentservice/data_sync.py
> +        if not self.celery:
Блин, не заметил 18-й строчки. Ок!

2017-06-23 21:58 UTC, dimka2014 commented on openprocurement/documentservice/data_sync.py
> +LOGGER = getLogger(__name__)
можем попасть под статью "Оскорбление чувств верующих", я бы не делал этого))

2017-06-23 23:03 UTC, merged